name: Docker Image CI
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag dvlpm/php8.1-dev:$(date +%s)
